sudo: required
services:
    - docker

before_install:
    - docker build -t taxkeller/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run taxkeller/react-test npm test -- --coverage

after_success:
    - docker build -t taxkeller/multi-client ./client
    - docker build -t taxkeller/multi-nginx ./nginx
    - docker build -t taxkeller/multi-server ./server
    - docker build -t taxkeller/multi-worker ./worker

deploy:
    provider: elasticbeanstalk
    region: ap-southeast-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-southeast-1-267823029828
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access:key: $AWS_SECRET_KEY
