sudo: required
services:
    - docker

before_install:
    - docker build -t taxkeller/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true taxkeller/react-test npm test

after_success:
    - docker build -t taxkeller/multi-client ./client
    - docker build -t taxkeller/multi-nginx ./nginx
    - docker build -t taxkeller/multi-server ./server
    - docker build -t taxkeller/multi-worker ./worker
